//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciciPasiona
{
    using System;
    using System.Collections.Generic;
    
    public partial class buys
    {
        public int id_buys { get; set; }
        public int manufacturer { get; set; }
        public int customer { get; set; }
        public Nullable<System.DateTime> buy_date { get; set; }
        public int units { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual manufacturers manufacturers { get; set; }
    }
}
