//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciciPasiona
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id_product { get; set; }
        public string title { get; set; }
        public Nullable<int> manufacturer { get; set; }
        public decimal price { get; set; }
    
        public virtual manufacturers manufacturers { get; set; }
    }
}
